items:
  - name: "default"
    heart amount: 1
    item:
      type: "paper"
      display name: "<color:#ff0000>Normal Heart</color>"
      lore:
        - "<gray>Right click to add <white>+1<color:#ff0000>❤</color></white> to your health"
      glint: true
      enchantments:
        - name: "unbreaking"
          level: 1
      custom model data: 144
      flags:
        - "hide enchants"

# The name of the item in the list above that should be dropped when a player dies
# To avoid confusion and misuse, this must exist in the "items" list above
# The amount of hearts the player will lose will be the same as the "heart amount" defined in the item (unless changed by other plugin that hooks into Lifestealer)
item to drop when player dies: "default"

# The amount of hearts a player should start with when they first join the server, a heart consists of 2 health points
starting hearts: 10

# Define rules that will change values based on player's permissions
rules:
  # The rules that will be applied to players that don't have any of the groups below (not to be confused with the "default" item, these are not related)
  default:
    # The maximum amount of hearts a player can have
    max hearts: 10
    # The minimum amount of hearts a player can have, if they lose more than this amount they will be banned
    min hearts: 5
    # The amount of time a player will be banned for if they lose more than the minimum amount of hearts
    ban time: 1d 12h 30m
    # The amount of hearts the player will have when they return from a ban
    return hearts: 7
  # Rules overrides applied to players with specific permissions
  groups:
    # If the player has permission "vip"
    - permission: "vip"
      # Change the maximum amount of hearts to 15
      max hearts: 15
      # and the minimum amount of hearts to 3
      min hearts: 3
      # The ban time and return hearts will be the same as the default
    # If the player has permission "admin"
    - permission: "admin"
      # Change the maximum amount of hearts to 20
      max hearts: 20
      # and the ban time to 0 seconds
      ban time: 15s
    # If the player has multiple groups, the overrides will be applied in the order they are defined here
    # So if a player has both "vip" and "admin" permissions, they will have:
    # - 20 max hearts
    # - 3 min hearts
    # - 15 seconds of ban time
    # - 7 return hearts

# Ban system configuration
# When a player loses more hearts than the minimum amount defined in the rules, they will be banned for the time defined in the rules
ban settings:
  # The message that will be sent to the player when they get banned and is online
  # For the duration placeholder check https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html for usage and more examples
  # For the date placeholder check https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html for usage and more examples
  kick message: "<red>You have been banned for <white><duration:'[d'd'H'h'm'm's's']'><red> for losing too many hearts.\nYou will be unbanned at <white><date:'yyyy-MM-dd HH:mm:ss'><red>."

  # The message that will be sent to the player when they try to join while banned
  # For the duration placeholder check https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html for usage and more examples
  # For the date placeholder check https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html for usage and more examples
  join message: "<red>You are banned for <white><remaining:'[d'd'H'h'm'm's's']'><red> for losing too many hearts.\nYou will be unbanned at <white><date:'yyyy-MM-dd HH:mm:ss'><red>."

  # The commands that will be executed by the console when a player gets bellow the minimum amount of hearts
  # The following placeholders can be used:
  # - <player>: the player's name that will be banned
  # - <duration>: the time in seconds the player will be banned for
  commands:
    - "say <player> has been eliminated for <duration>s for losing too many hearts (remove this message in the config)"
  #    - "ban <player> <duration> Hearts lost"

  # If you want to not use the ban system of Lifestealer and wish to use your own, set this to true
  # This will prevent the plugin from banning players or not allow them to join the server
  #
  # The commands in "commands" will still be executed even if this is set to true
  # and will also save the player ban status internally in the database but won't use
  # it for anything (you can lookup that data using the developer API)
  external: false

messages:
  # The messages that will be sent to the player when they perform certain actions
  #
  # These messages have many components such as chat message, action bar message,
  # title, subtitle, sound and more which you can combine to create complex interactions.
  #
  # The chat, action bar, title and subtitle components are formatted using the MiniMessage format.
  # Check https://docs.adventure.kyori.net/minimessage.html for more information and examples.
  #
  # Examples:

  # » message key: "<red>Hello"
  # Sends a red chat message to the player

  # » message key:
  #     message: "<red>Hello"
  #     action bar: "<yellow>World"
  # Sends a red chat message and a yellow action bar message to the player

  # » message key:
  #     title: "<green>Hi"
  #     subtitle: "<blue>There"
  # Sends a green title and a blue subtitle to the player

  # » message key:
  #     title: "<green>Hi"
  #     subtitle: "<blue>There"
  #     title times:
  #       fade in: 10
  #       stay: 20
  #       fade out: 10
  # Sends a green title and a blue subtitle to the player with the specified fade in, stay and fade out times (in ticks)

  # » message key:
  #     title: "<green>Hi"
  #     sound: minecraft:entity.player.levelup
  # Sends a green title to the player and plays the level up sound

  # » message key:
  #     action bar: "<green>Hi"
  #     sound:
  #       key: minecraft:entity.player.levelup
  #       volume: 0.5
  #       pitch: 0.2
  # Sends a green action bar message to the player and plays the level up sound with a volume of 0.5 and a pitch of 0.2

  command hearts set success: "<green>Set <white><target><green>'s hearts to <white><new><color:#ff0000>❤</color><green> (old: <white><previous><color:#ff0000>❤</color><green>)."
  command hearts set success target:
    sound: minecraft:entity.player.levelup
  command hearts add success: "<green>Added <white><added><green><color:#ff0000>❤</color> to <white><target><green> (new: <white><new><color:#ff0000>❤</color><green>, old: <white><previous><color:#ff0000>❤</color><green>)."
  command hearts add success target:
    sound:
      key: minecraft:entity.player.levelup
      volume: 0.5
      pitch: 0.2
  command hearts remove success: "<green>Removed <white><removed><green><color:#ff0000>❤</color> from <white><target><green> (new: <white><new><color:#ff0000>❤</color><green>, old: <white><previous><color:#ff0000>❤</color><green>)."
  command hearts remove success target:
    sound: minecraft:entity.player.hurt
  command item give success: "<green>Gave <white>x<amount> <item></white> heart item to <white><target><green> (<white><rest></white> could not be given due to full inventory)."
  command item give success target:
    action bar: "<green>Received <white>x<amount> <item></white> heart items."
  command item take success: "<green>Removed <white>x<amount> <item></white> heart item from <white><target><green> (<white><rest></white> could not be removed due to not having enough)."
  command item take success target:
    action bar: "<red>Lost <white>x<amount> <item></white> heart items."
  # For the duration placeholder check https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html for usage and more examples
  command ban success: "<green>Force banned <white><target></white> for <white><duration:'[d'd'H'h'm'm's's']'></white> (date: <white><date:'yyyy-MM-dd HH:mm:ss'></white>)."
  command unban success: "<green>Unbanned <white><target></white>."
  command unban not banned: "<red><white><target></white> is not banned."
  consume heart success:
    action bar: "<white>+<amount><color:#ff0000>❤</color>"
    sound: minecraft:entity.player.levelup
  consume heart already full:
    action bar: "<red>You can't consume any more hearts."
    sound: minecraft:entity.villager.no