items:
  - name: "default"
    heart amount: 1
    item:
      type: "paper"
      display name: "<color:#ff0000>Normal Heart</color>"
      lore:
        - "<gray>Right click to add <white>+1<color:#ff0000>♥</color></white> to your health"
      glint: true
      enchantments:
        - name: "unbreaking"
          level: 1
      custom model data: 144
      flags:
        - "hide enchants"
starting hearts: 10
rules:
  default:
    max hearts: 10
    min hearts: 5
    ban time: 1d 12h 30m
  groups:
    - permission: "vip"
      max hearts: 15
      min hearts: 3
    - permission: "admin"
      max hearts: 20
      ban time: 0s