services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - "3306:3306"
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: 'mariadb'
      MARIADB_ROOT_PASSWORD: '12345678'
    ports:
      - "3306:3306"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: 'postgres'
    ports:
      - "5432:5432"