name: Build Javadoc

on:
  push:
    branches:
      - main

jobs:
  javadocs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 21
          target-folder: .
          project: gradle
          
